server:
  port: 18081

spring:
  application:
    name: user-consumer

dubbo:
  application:
    name: user-consumer
    qos-enable: false
  registry:
    address: nacos://127.0.0.1:8848
    register: true
    # subscribe: true
  consumer:
    check: false
    # timeout: 5000
    # retries: 2
  protocol:
    port: -1


logging:
  level:
    org.apache.dubbo: DEBUG
    com.module.consumer: DEBUG
