server:
  port: 18081

spring:
  application:
    name: user-consumer

dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: nacos://127.0.0.1:8848
  consumer:
    timeout: 3000
    version: 1.0.0
    group: default
