server:
  port: 18080

spring:
  application:
    name: user-provider
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dubbo-module?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456


mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.module.api.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

dubbo:
  application:
    name: ${spring.application.name}
    qos-enable: false

  registry:
    address: nacos://127.0.0.1:8848
    check: true

  protocol:
    name: dubbo
    port: 20880

  provider:
    version: 1.0.0
    group: default
    timeout: 3000
    retries: 2
    loadbalance: roundrobin
    actives: 100
    delay: 0

  scan:
    base-packages: com.module.userprovider.service.impl